# Site settings
title: BY Blog
SEOTitle: 柏荧的博客 | BY Blog
header-img: img/post-bg-desk.jpg
email: qiubaiying@gmail.com
description: "Every failure is leading towards success."
keyword: "BY, BY Blog, 柏荧的博客, qiubaiying, 邱柏荧, iOS, Apple, iPhone"
url: "http://hlwdy.github.io/blog"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/hlwdy/hlwdy.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you going to be!"
